---
monpi.lan:
    hostname: monpi.lan
    port: 22
    platform: linux
    groups:
        - pi

netpi.lan:
    hostname: netpi.lan
    port: 22
    platform: linux
    groups:
        - pi

vanilla.lan:
    hostname: vanilla.lan
    port: 22
    platform: linux
    groups:
        - vm