---
dalinar.lan:
    hostname: dallanar
    port: 22
    platform: linux
    groups:
        - host

monpi.lan:
    hostname: monpi
    port: 22
    platform: linux
    groups:
        - pi

netpi.lan:
    hostname: netpi
    port: 22
    platform: linux
    groups:
        - pi

samba.lan:
    hostname: samba
    port: 22
    platform: linux
    groups:
        - vm

vanilla.lan:
    hostname: vanilla
    port: 22
    platform: linux
    groups:
        - vm

browser.lan:
    hostname: vanilla
    port: 22
    platform: linux
    groups:
        - vm