---
monpi:
    hostname: monpi.lan
    port: 22
    platform: linux
    groups:
        - pi

netpi:
    hostname: netpi.lan
    port: 22
    platform: linux
    groups:
        - pi

vanilla:
    hostname: vanilla.lan
    port: 22
    platform: linux
    groups:
        - vm