---
monpi.lan:
    hostname: monpi
    port: 22
    platform: linux
    groups:
        - pi

netpi.lan:
    hostname: netpi
    port: 22
    platform: linux
    groups:
        - pi

vanilla.lan:
    hostname: vanilla
    port: 22
    platform: linux
    groups:
        - vm